name: Proton nopackage Ubuntu CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      
      - name: Compile
        run: |
          export CARGO_HOME="$PWD"
          sudo dpkg --add-architecture i386
          sudo apt update          
          rustup target add i686-unknown-linux-gnu
          cd proton-tkg
          sudo wget https://github.com/torvalds/linux/raw/refs/tags/v6.14/include/uapi/linux/ntsync.h -O /usr/include/linux/ntsync.h
          sed -i 's/uninstaller=\"false\"/uninstaller=\"true\"/' proton-tkg.cfg
          sed -i 's/autoinstall=\"false\"/autoinstall=\"true\"/' proton-tkg.cfg
          sed -i 's/LOCAL_PRESET=\"\"/LOCAL_PRESET=\"none\"/' proton-tkg.cfg
          #sed -i 's/build_gstreamer=\"false\"/build_gstreamer=\"true\"/' proton-tkg.cfg
          #sed -i 's/lib32_gstreamer=\"false\"/lib32_gstreamer=\"true\"/' proton-tkg.cfg
          sed -i 's/_NOLIB32="false"/_NOLIB32="wow64"/' ../wine-tkg-git/wine-tkg-profiles/advanced-customization.cfg
          sed -i 's/_use_ntsync=\"false\"/_use_ntsync=\"true\"/' proton-tkg.cfg
          sed -i 's/_use_esync=\"true\"/_use_esync=\"false\"/' proton-tkg.cfg
          sed -i 's/_use_fsync=\"true\"/_use_fsync=\"false\"/' proton-tkg.cfg
          echo '_ci_build="true"' >> proton-tkg.cfg
          touch tarplz
          yes|./proton-tkg.sh
          

      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proton-tkg-build
          path: proton-tkg/built/*.tar
