name: Wine Ubuntu CI

on:
  schedule:
    - cron:  '25 9,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'
          cd wine-tkg-git 
          sed -i 's/_NOLIB32="false"/_NOLIB32="false"/' wine-tkg-profiles/advanced-customization.cfg
          echo '_ci_build="true"' >> customization.cfg
          sudo wget https://github.com/torvalds/linux/raw/refs/tags/v6.14/include/uapi/linux/ntsync.h -O /usr/include/linux/ntsync.h
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-tkg-build
          path: wine-tkg-git/non-makepkg-builds
